### ISSUE TITLE
Implement RIO plugins

### ISSUE THREAD

**Issue by oddcoder** [Rair-Project/rair-core#17]
- [x] `srec://` Motorola S-record file encoding. Done via #62 
- [x]  `base64://` for loading base64 file formats. Done via #61 
- [x]  `malloc://` for memory allocation based files. Done via #60 
- [x]  Allow opening files in COW( Copy-On-Write mode). Done via #55  ~`cow://`: open file as read write except for data is not written the real file itself. instead to a memory copy~. 
- [x] `ihex://` : load Intel Ihex File coding. Done via #57

**Comment by oddcoder** [comment]
probable copy on write need not be a file plugin but rather a IoMode options.
