### ISSUE TITLE
0.1 List of commands that are missing

### ISSUE THREAD

**Issue by oddcoder** [Rair-Project/rair-core#49]
- [x] Commands to open close and list files. Done via #63 .

- [x] commands to print data stream with varios bases. Done via #64 .

- [x] Command to write into file (`wx` and variations). Done via #65 .

- [x] Command to write from memory to file (similar to wtf in radare2). Done via #65.
- [ ] ~Command to list IO plugin.~
- [ ] ~`?` Command to list help everything.~
