### ISSUE TITLE
Add suport for envirionment variables

### ISSUE THREAD

**Issue by oddcoder** [Rair-Project/rair-core#54]
basically I have these in mind.

- [x] color palettes. (via #74 )
- [x] Enable/disable coloring. (via #75)
- [x] Which colors does each command use from the palettes. (via #76)
- [ ] Auto update.
- [ ] how the prompt looks like.

~Allow custom plugins environment variables. plugin like ihex would need env var like checksume= true or false~ this will be hard to utilize or even impossible.

**Comment by oddcoder** [comment]
The rest are moved to rair https://github.com/Rair-Project/rair/issues/7.
